// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXlBEQjw-rufI7XKEsRqKtAw3Wud-rRt4',
    appId: '1:878703156302:web:d1677f2b27a44de7f3371f',
    messagingSenderId: '878703156302',
    projectId: 'booming-bonito-485111-m0',
    authDomain: 'booming-bonito-485111-m0.firebaseapp.com',
    storageBucket: 'booming-bonito-485111-m0.firebasestorage.app',
    measurementId: 'G-P470J6MF6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF3Az89cjQ0uaTVByLEXbJYkPhYXF2Ghc',
    appId: '1:878703156302:android:75b98432a9f77733f3371f',
    messagingSenderId: '878703156302',
    projectId: 'booming-bonito-485111-m0',
    storageBucket: 'booming-bonito-485111-m0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuE8dW8dTJHZ7WYcg4YPKK7Mru8IVGRxo',
    appId: '1:878703156302:ios:77be5fade79cfcfff3371f',
    messagingSenderId: '878703156302',
    projectId: 'booming-bonito-485111-m0',
    storageBucket: 'booming-bonito-485111-m0.firebasestorage.app',
    iosBundleId: 'com.example.medrepo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuE8dW8dTJHZ7WYcg4YPKK7Mru8IVGRxo',
    appId: '1:878703156302:ios:77be5fade79cfcfff3371f',
    messagingSenderId: '878703156302',
    projectId: 'booming-bonito-485111-m0',
    storageBucket: 'booming-bonito-485111-m0.firebasestorage.app',
    iosBundleId: 'com.example.medrepo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXlBEQjw-rufI7XKEsRqKtAw3Wud-rRt4',
    appId: '1:878703156302:web:f74b37d0bcf04bc3f3371f',
    messagingSenderId: '878703156302',
    projectId: 'booming-bonito-485111-m0',
    authDomain: 'booming-bonito-485111-m0.firebaseapp.com',
    storageBucket: 'booming-bonito-485111-m0.firebasestorage.app',
    measurementId: 'G-QBWMN4PG3T',
  );
}
